config/routes.rb
Rails.application.routes.draw do

  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'

  resources :frienships
  resources :sessions
  resources :users, only: [:index, :show, :create, :new, :destroy, :edit, :update]
  get   '/search', to: 'users#search'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/newfriendship',  to: 'friendships#add_friend', as: "add_new_friend"
  post '/endfriendship', to: 'friendships#delete_friend', as: "unfollow_friend"
  post '/sessions/:id',  to: 'sessions#destroy'
  # get    '/signup',  to: 'users#new'
  # post    '/signup',  to: 'users#new'
  # delete '/logout',  to: 'sessions#destroy'
  # get    '/users/:id/edit', to: 'users#edit'
  # patch  '/users/:id', to: 'users#update'
  # delete  '/users/:id/edit', to: 'users#destroy'
  # get 'users/new', to: "users#new", as: "signup"
  # post 'users/new', to: "users#create"
  # resources :friendships, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Friendship'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Friendship'
  has_many :followers, through: :following_users
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :telephone_number, presence: true

  def img_url=(value)
    if value.blank?
      write_attribute :img_url, 'https://user-images.githubusercontent.com/16608864/35882949-bbe13aa0-0bab-11e8-859c-ceda3b213818.jpeg'
    else
      write_attribute :img_url, value
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def self.search(search)
    search_results = where('first_name LIKE ?', "%#{search}%")
      if search_results.count > 0
        search_results
      else
        all
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized #lock down this whole app
  helper_method :current_user, :logged_in? #i can call current_user from a view

   def current_user
     # User.find would throw an error if we cannot find the user
     User.find_by({ id: session[:user_id] })
   end
   #
   def logged_in?
     # nil is falsey in ruby
     # a user instance is truthy
     !!current_user
   end
   #
   def authorized
     redirect_to login_path unless logged_in?
   end

  end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def add_friend
    @user = User.find(params[:followee_id])
    @new_friendship = Friendship.find_by(follower_id: current_user.id, followee_id: @user.id)
    if @user.id == current_user.id
      redirect_to current_user
      flash[:notice] = "You already know your birthday!"
    elsif @new_friendship == nil
      Friendship.create(follower_id: current_user.id, followee_id: @user.id)
      redirect_to current_user
      flash[:notice] = "You now follow #{@user.name}"
      else
    redirect_to current_user
    flash[:notice] = "You already follow #{@user.name}"
      end
  end

  def delete_friend
    @user = User.find(params[:followee_id])
    @unfollow = Friendship.find_by(follower_id: current_user.id, followee_id: @user.id)
    @unfollow.destroy
    redirect_to current_user
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #before_action :authorized comes from ApplicationController
  skip_before_action :authorized, only: [:new, :create, :destroy]

  def new
    render :new #looks in app/views/sessions/new.html.erb
  end

  def create #handles the POST request to /login
    # find out if we have a user with this username
    @user = User.find_by(username: params[:username])
    # get that user record from DB
    # authenticate this user; determine if they provided the correct pw

    if @user && @user.authenticate(params[:password])
      # once we have found the user, create a new session for them
      session[:user_id] = @user.id
      # redirect_to user_path(@user)
      redirect_to @user
    else
      flash[:notice] = 'Invalid username or password'
      redirect_to login_path
    end
  end

  def destroy
   session[:user_id] = nil
   redirect_to login_path, notice: "You are now logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :destroy]

  def index
      @users = User.search(params[:search])
  end

  def new
    @user = User.new
  end

  def create
      @user = User.create(user_params)
     if @user.valid?
       session[:user_id] = @user.id
       redirect_to user_path(@user), notice: "Signup successful!"
     else
       flash[:errors] = @user.errors.full_messages
       render new_user_path
     end
  end

  def edit
    @user = User.find(params[:id])
      if current_user == @user
      else redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
	  redirect_to login_path
  end


  def show

   @user = User.find(params[:id])
   @who_follows_you = @user.followers
   @who_you_follow = @user.followees

  #   birthday.month == Time.now.month &&
    @who_you_follow.each do |user|

      if user.birthday.day == Time.now.day && user.birthday.month == Time.now.month

        flash[:birthday_notice] = "It is your friend #{user.name}'s birthday!"
      end
    end
  end

private

def user_params
    params.require(:user).permit(:first_name, :last_name, :birthday, :telephone_number, :img_url, :username, :email, :password, :search)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"></a>
  <img src="https://imgur.com/ICcTgsz.jpg" width="30" height="30" class="d-inline-block align-top" alt="">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">BirthdayBook <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users">Search For Friends<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/<%= current_user.id %>">My Profile<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>BirthdayBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <header>
    <% if logged_in? %>
     <%= render 'layouts/navigation' %>
   <% end %>
   </header>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<br>
<br>
<div align="center">
<h1>Edit Your Profile</h1>
<br>
<br>

<%=form_for @user do |f|%>
<%=f.label :username%><br>
<%=f.text_field :username%><br>
<br>
<%=f.label :first_name%><br>
<%=f.text_field :first_name%><br>
<br>
<%=f.label :last_name%><br>
<%=f.text_field :last_name%><br>
<br>
<%=f.label :email%><br>
<%=f.text_field :email%><br>
<br>
<%=f.label :birthday%><br>
<%=f.date_select :birthday, :order => [:month, :day, :year], :start_year => 1900, :end_year => Time.now.year%><br>
<br>
<%=f.label :telephone_number%><br>
<%=f.text_field :telephone_number%><br>
<br>
<%=f.label :img_url%><br>
<%=f.text_field :img_url%><br>
<br>
<%=f.submit %>
<%end%>
<br>
<br>

<%= button_to "Delete Account", @user, :method => :delete, data: { confirm: "Are you sure you want to delete your account?" } %>

</div>
<br>
<br>

app/views/users/index.html.erb
<br>
<br>
<div class="container">
<div align="center">
<h1>BirthdayBook Users</h1>
<br>
<%= form_tag(users_path, method: :get) do %>
 Name <%= text_field_tag :search, params[:search]%>
 <%= submit_tag 'Search', search: nil %>
 <% end %>
<br>
<br>

<% @users.in_groups_of(4) do |user| %>
  <div class="row">
    <% user.compact.each do |user| %>
      <div class="col-md-3">
        <h4><%= link_to user.name, user %></h4>
        <h5>Birthday: <%= user.birthday.to_formatted_s(:long) %></h5>
        <%=image_tag user.img_url, width: '250px', height: '250px'%><br>
        <br>
        <%= button_to"Follow", add_new_friend_path, :method => :post, params: {followee_id: user.id}, class: 'btn btn-primary' %>
        <br>
      </div>
      <% end %>
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<br>
<br>
<div align="center">
<h1>Create your profile</h1>
<br>
<br>

<% if !!flash[:errors] %>
  <div class="alert alert-dismissible alert-primary">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
      <% flash[:errors].each do |e| %>
        <strong>  <p><%= e %></p><strong>
      <% end %>
    <% end %>
</div>

<div align="center">
<%=form_for @user do |f|%>
<%=f.label :username%><br>
<%=f.text_field :username%><br>
<br>
<%=f.label :password%><br>
<%=f.text_field :password%><br>
<br>
<%=f.label :first_name%><br>
<%=f.text_field :first_name%><br>
<br>
<%=f.label :last_name%><br>
<%=f.text_field :last_name%><br>
<br>
<%=f.label :email%><br>
<%=f.text_field :email%><br>
<br>
<%=f.label :birthday%><br>
<%=f.date_select :birthday, :order => [:month, :day, :year], :start_year => 1900, :end_year => Time.now.year%><br>
<br>
<%=f.label :telephone_number%><br>
<%=f.text_field :telephone_number%><br>
<br>
<%=f.label :img_url%><br>
<%=f.text_field :img_url%><br>
<br>
<%=f.submit %>
<%end%>

</div>
<br>
<br>

app/views/users/show.html.erb
<br>
<br>
<div align="center">
<%if flash[:notice] %>
<div class="alert alert-dismissible alert-info">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<strong><%= flash[:notice] %></strong>
</div>
</div>
<%end %>


<div class="container">
  <div align="center">
    <% if flash[:birthday_notice] %>
    <div class="alert alert-dismissible alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong><%= flash[:birthday_notice] %></strong>
    </div>
    </div>
    <%end %>
  </div>
</div>
<br>
<div class="container">
  <div align="center">
    <% if current_user == @user %>
    <h1><%= "Your Profile Page" %></h1>
    <% else %>
    <h1><%= "#{@user.name}'s Profile"%></h1>
    <%end %><br>
    <h2><img src="<%=@user.img_url%>" width="200px" height="200px"></h2>
    <h3>Name: <%=@user.name%></h3>
    <h5>Phone Number: <%=@user.telephone_number%></h5>
    <h5>Birthday: <%=@user.birthday.to_formatted_s(:long)%></h5>

    </div>
</div>
<br>
<div class="container">
  <div align="center">


    <% if current_user == @user %>
    <h5>Who you follow: </h5>
    <br>
    <br>
    <% @who_you_follow.in_groups_of(4) do |follow| %>
    <div class="row">
    <% follow.compact.each do |follow| %>
    <div class="col-md-3">
    <img src="<%=follow.img_url%>" width="150px" height="150px"><br>
    <%= link_to follow.name, "/users/#{follow.id}" %><br>
    <%=follow.birthday.to_formatted_s(:long)%>
    <br>
    <%= button_to "Unfollow", unfollow_friend_path, :method => :post, params: {followee_id: follow.id}, class: 'btn btn-primary' %>
    <br>
  </div>
  <% end %>
  </div>
  <% end %>
  <% end %>

    <% if current_user != @user %>
      <%= button_to"Add Friend", add_new_friend_path, :method => :post, params: {followee_id: @user.id}, class: 'btn btn-primary' %>
    <%end%>

    <% if current_user == @user %>
    <%= link_to "Edit Profile", edit_user_path(current_user.id)%>
    <% end %>
    <br>
    <br>
<%= button_to "Logout", :controller=> "sessions", :action=> "destroy"%>
  </div>
</div>